### ISSUE TITLE
FileManager : trouble downloading large file (>1Go)

### ISSUE THREAD

**Issue by WagnerGMD** [nelu/rutorrent-thirdparty-plugins#13]
Hello,

the FileManager isn't **fully** reliable because at the end, the file is corrupted (or damaged). And that's right, I made several attempts and it's always the same result.
The downloading of large file (somewhere about 1,20 Go or little more) doesn't work like excepted. The file seem's complete but it's almost a lie. If you take a look (more precise) and check the hash (md5 etc), well it is not the same.
And if I use something else (via FTP etc) to download any files, I don't met the trouble.

I don't know if you're aware of this bug. And I ignore how to fix it ? There's something wrong with the plugin itself or it's something about the web server ? Maybe it's the configuration of **Nginx** or the **PHP** (aka php5-fpm) ?
I assume, it's about the **FastCGI** but what ?

If you have one idea, it would be appreciate.
Have a good day.

PS : I could be patient but none sign of live... 3 months in few days...

**Comment by artyuum** [comment]
I think this issue is related to ruTorrent and not filemanager as the plugin uses the "sendfile" function from ruTorrent core.
flm : https://github.com/nelu/rutorrent-thirdparty-plugins/blob/stable/filemanager/flm.php#L25
ruTorrent : https://github.com/Novik/ruTorrent/blob/10c6927b1a2d7370e59d697584a8c8913eb94d98/php/util.php#L556

**Comment by nelu** [comment]
ruTorrent sendFile issue. but it should work
https://github.com/nelu/rutorrent-thirdparty-plugins/blob/stable/filemanager/flm.class.php#L580
this method can be used instead.
